schedules:
- cron: "0,20,40 * * * *"
  displayName: status page update
  branches:
    include:
    - azure-cron
    exclude:
    - master
    - heartbeats
  always: true

jobs:
- job: update_status_page
  pool:
    vmImage: 'Ubuntu-16.04'
  timeoutInMinutes: 360

  steps:

  - checkout: self
    clean: true

  - bash: .ci_scripts/install_miniconda.sh
    displayName: install miniconda

  - bash: |
        git config --global user.name regro-cf-autotick-bot
        git config --global user.email circleci@cf-graph.regro.github.com
        git config --global pull.rebase false

    displayName: configure git

  - bash: |
        set -e
        source $HOME/miniforge3/etc/profile.d/conda.sh
        conda activate base
        cat .ci_scripts/condarc > $HOME/.condarc

        export START_TIME=$(date +%s)
        export TIMEOUT=7200

        git clone https://github.com/regro/cf-scripts.git
        pushd cf-scripts

        export GIT_FULL_HASH=$(git rev-parse HEAD)
        conda create -n run_env --quiet --file requirements/run
        source activate run_env

        conda info
        conda config --show-sources
        conda list --show-channel-urls
        python setup.py develop
        popd
        git clone --depth=1 https://github.com/regro/cf-graph-countyfair.git cf-graph
        git clone --depth=1 https://github.com/conda-forge/conda-forge-pinning-feedstock.git

    displayName: clone and setup

  - bash: |
        set -e
        source $HOME/miniforge3/etc/profile.d/conda.sh
        conda activate base
        cat .ci_scripts/condarc > $HOME/.condarc

        pushd cf-graph
        source activate run_env

        conda-forge-tick --run 4

        popd

    displayName: update status page

  - bash: |
        set -e
        source $HOME/miniforge3/etc/profile.d/conda.sh
        conda activate base
        cat .ci_scripts/condarc > $HOME/.condarc

        pushd cf-graph
        source activate run_env

        export CIRCLE_BUILD_URL="https://dev.azure.com/conda-forge/regro/_build/results?buildId=${BUILD_BUILDID}&view=results"
        export CIRCLE_BUILD_NUM="actually-azure-${BUILD_BUILDID}"

        conda-forge-tick --run -1

        popd

    displayName: deploy
    env:
      PASSWORD: $(password)
